name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: "1.0"
  DOCKER_USER: maisabbispo
  DOCKER_IMAGE_NAME: maisabbispo/mundo-global
  SERVICE_NAME: mundo-global

jobs:
  create-images:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }} app/.

      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}

  run-docker:
    name: Deploy Container
    runs-on: ubuntu-latest
    needs: create-images

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Remove Existing Container (if exists)
        run: docker rm -f app-docker || true

      - name: Pull New Image
        run: docker pull ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}

      - name: Run Container
        run: docker run -dti -p 8080:8080 --name app-docker ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}
